httpd:
 build: ./httpd/
 links:
  - app:tomcat
 ports:
  - 80:80
db:
  build: ./bbdd/
  ports:
    - 3306:3306
  environment:
    MYSQL_USER : user
    MYSQL_PASSWORD : password
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: test
app:
  build: ./app/
  links:
    - db:db
  ports:
   - 8080:8080
